// lib/guias.ts
// Os textos da página de Ajuda (lib/ajuda.ts). Cada guia é uma tarefa, contada para quem nunca usou o
// sistema: passos curtos, com o nome exato de cada botão em **negrito**. Ao mudar uma tela, mudar o guia
// dela junto. O teste de lib/ajuda confere que o "Ir para" de cada guia abre para todos os papéis dele.
import type { Guia, Papel } from "@/lib/ajuda";

const TODOS: Papel[] = ["admin", "coordenador", "funcionario", "profissional", "familiar"];
const GESTAO: Papel[] = ["admin", "coordenador", "funcionario"];
const EQUIPE: Papel[] = [...GESTAO, "profissional"];

export const GUIAS: Guia[] = [
  // ——— Primeiros passos ———
  {
    id: "conhecer-o-menu",
    titulo: "Conhecer o menu e a tela inicial",
    assunto: "comecar",
    papeis: TODOS,
    resumo: "O menu é o mapa do sistema: ele mostra só as telas que você usa.",
    passos: [
      {
        texto: "No celular, toque no botão de **menu**, no canto de cima, à esquerda. No computador, o menu já fica aberto do lado esquerdo.",
      },
      { texto: "Toque no nome de uma tela para abrir. Para voltar ao começo, toque em **Dashboard**.", mini: { tipo: "opcoes", itens: ["Dashboard", "Agendamentos", "Avisos", "Mensagens"], escolhida: "Dashboard" } },
      { texto: "O **sino**, no alto da tela, leva aos Avisos. Uma bolinha vermelha nele quer dizer que chegou aviso novo." },
      { texto: "Suas iniciais, no canto de cima, à direita, abrem **Configurações** (seu nome e sua senha) e **Sair**." },
    ],
    dica: "No computador, onde os guias dizem \"toque\", é só clicar.",
    tela: { href: "/", rotulo: "Ir para a tela inicial" },
    relacionados: ["instalar-no-celular", "minha-conta"],
  },
  {
    id: "instalar-no-celular",
    titulo: "Instalar o Libelle no celular",
    assunto: "comecar",
    papeis: TODOS,
    resumo: "O site vira um aplicativo na tela do celular: abre com um toque, sem digitar o endereço.",
    passos: [
      { texto: "Abra o site no celular e toque em **Instalar app**, no alto da tela, ao lado do sino.", mini: { tipo: "botao", texto: "Instalar app", variante: "contorno" } },
      { texto: "No Android, toque em **Instalar** na janela que aparece. No iPhone, siga os 3 passos que aparecem na tela." },
      { texto: "Pronto: a libélula aparece junto com os seus apps. Da próxima vez, abra por ela." },
    ],
    dica: "O botão não aparece? Ele some depois de instalado e quando alguém toca no ×. Dá para instalar pelo navegador: no iPhone, **Compartilhar** e depois **Adicionar à Tela de Início**; no Android, **três pontinhos** e depois **Instalar app**.",
  },
  {
    id: "minha-conta",
    titulo: "Mudar o meu nome ou a minha senha",
    assunto: "comecar",
    papeis: TODOS,
    resumo: "Seu nome aparece para a equipe; a senha é só sua.",
    passos: [
      { texto: "Toque nas suas iniciais, no canto de cima, à direita, e depois em **Configurações**." },
      { texto: "Para mudar o nome: em **Perfil**, corrija o **Nome Completo** e toque em **Salvar Alterações**.", mini: { tipo: "campo", rotulo: "Nome Completo", exemplo: "Maria da Silva" } },
      { texto: "Para mudar a senha: em **Segurança**, escreva a **Nova Senha** duas vezes e toque em **Atualizar Senha**." },
    ],
    dica: "O e-mail de acesso não pode ser mudado por aqui. Se precisar, fale com a administração.",
    tela: { href: "/minha-conta", rotulo: "Ir para Minha Conta" },
  },
  {
    id: "sair",
    titulo: "Sair do sistema",
    assunto: "comecar",
    papeis: TODOS,
    resumo: "Em computador ou celular que outras pessoas usam, saia sempre no fim do dia.",
    passos: [
      { texto: "Toque nas suas iniciais, no canto de cima, à direita." },
      { texto: "Toque em **Sair**.", mini: { tipo: "botao", texto: "Sair", variante: "perigo" } },
    ],
  },
  {
    id: "proximos-atendimentos",
    titulo: "Ver os próximos atendimentos",
    assunto: "comecar",
    papeis: ["familiar"],
    resumo: "A tela inicial mostra as próximas sessões da sua criança na clínica.",
    passos: [
      { texto: "Abra o sistema. A primeira tela já mostra os **Próximos Atendimentos**.", mini: { tipo: "item", titulo: "Fonoaudiologia", detalhe: "Terça, 09:00", selo: "Agendado" } },
      { texto: "Cada atendimento mostra o dia, o horário e a terapia." },
      { texto: "Para falar com a equipe, toque em **Falar com a equipe**, em **Acesso Rápido**." },
    ],
    dica: "Não aparece nenhum atendimento? Confira com a recepção se o e-mail da sua conta é o mesmo que está na ficha da criança.",
    tela: { href: "/", rotulo: "Ir para a tela inicial" },
    relacionados: ["conversar-mensagens"],
  },

  // ——— Agenda ———
  {
    id: "minhas-sessoes-do-dia",
    titulo: "Ver as minhas sessões do dia",
    assunto: "agenda",
    papeis: ["profissional"],
    resumo: "A agenda abre nas suas sessões de hoje, com horário, criança, terapia e sala.",
    passos: [
      { texto: "No menu, toque em **Agendamentos**." },
      { texto: "Deixe marcado **Minhas sessões**. Em **Clínica toda**, aparecem as sessões de todos os terapeutas.", mini: { tipo: "opcoes", itens: ["Minhas sessões", "Clínica toda"], escolhida: "Minhas sessões" } },
      { texto: "Para ver outro dia: no celular, use as setas **‹** e **›** ao lado da data; no computador, mude a **Data**." },
    ],
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
    relacionados: ["minha-semana-na-grade"],
  },
  {
    id: "minha-semana-na-grade",
    titulo: "Ver a minha semana na grade",
    assunto: "agenda",
    papeis: ["profissional"],
    resumo: "A grade mostra a sua semana inteira, horário por horário.",
    passos: [
      { texto: "Em **Agendamentos**, toque em **Ver minha semana na grade**, no fim da lista.", mini: { tipo: "botao", texto: "Ver minha semana na grade", variante: "contorno" } },
      { texto: "No celular, toque num dia da semana, em cima, para ver as sessões dele. No computador, a semana aparece inteira." },
      { texto: "Use as setas para ir para a **Próxima semana** ou voltar para a **Semana anterior**." },
    ],
    dica: "A grade é só para consultar. Para mudar um horário, fale com a recepção.",
    tela: { href: "/agendamentos/terapeuta", rotulo: "Ir para a minha grade" },
  },
  {
    id: "sessoes-do-dia",
    titulo: "Ver as sessões do dia",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "A agenda mostra todas as sessões da clínica no dia escolhido.",
    passos: [
      { texto: "No menu, toque em **Agendamentos**. A tela abre no dia de hoje." },
      { texto: "Para ver outro dia: no celular, use as setas **‹** e **›** ao lado da data; no computador, mude a **Data**." },
      { texto: "Para achar alguém, toque em **Filtros**: dá para buscar pelo nome do paciente, pelo profissional e pelo status.", mini: { tipo: "campo", rotulo: "Buscar por Nome do Paciente", exemplo: "Nome do paciente..." } },
    ],
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
    relacionados: ["presenca-falta", "marcar-uma-sessao"],
  },
  {
    id: "marcar-uma-sessao",
    titulo: "Marcar uma sessão",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Marca uma sessão avulsa ou um horário que se repete toda semana.",
    passos: [
      { texto: "Em **Agendamentos**, toque em **Novo Agendamento** e depois em **Agendamento Único/Sequencial**. No celular, o botão é o **+**.", mini: { tipo: "botao", texto: "+ Novo Agendamento", variante: "principal" } },
      { texto: "Escolha o **Paciente**, o **Profissional** e a **Especialidade**." },
      { texto: "Preencha a **Data**, o **Horário Inicial** e o **Horário Final**. A **Sala** é opcional." },
      { texto: "Se a sessão se repete, ligue **Criar agendamento recorrente** e escolha a **Frequência** e o **Número de Sessões**.", mini: { tipo: "chave", rotulo: "Criar agendamento recorrente", ligada: true } },
      { texto: "Toque em **Salvar Agendamento(s)**.", mini: { tipo: "botao", texto: "Salvar Agendamento(s)", variante: "principal" } },
    ],
    dica: "Para achar um horário livre olhando a semana inteira, use a grade: veja o guia logo abaixo.",
    tela: { href: "/agendamentos/novo", rotulo: "Ir para Novo Agendamento" },
    relacionados: ["agendar-pela-grade"],
  },
  {
    id: "agendar-pela-grade",
    titulo: "Achar um horário livre e agendar pela grade",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "A grade mostra a semana de uma criança: os buracos são os horários livres.",
    passos: [
      { texto: "Em **Agendamentos**, toque em **Ver grade** e depois em **Grade por paciente**." },
      { texto: "Em **Selecione o Paciente**, escolha a criança." },
      { texto: "Toque num horário vazio. No celular, escolha o dia em cima e toque em **+ Agendar**.", mini: { tipo: "botao", texto: "+ Agendar", variante: "contorno" } },
      { texto: "Na janela **Agendamento Rápido**, escolha o profissional e a especialidade e toque em **Adicionar à Grade**. A sessão aparece como **Pendente**." },
      { texto: "Repita para os outros horários e, no fim, toque em **Salvar Agenda**.", mini: { tipo: "botao", texto: "Salvar Agenda (2)", variante: "principal" } },
    ],
    dica: "Enquanto você não toca em **Salvar Agenda**, nada fica gravado.",
    tela: { href: "/agendamentos/grade", rotulo: "Ir para a grade por paciente" },
  },
  {
    id: "presenca-falta",
    titulo: "Marcar presença, falta ou cancelamento",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Depois de cada sessão, marque o que aconteceu. Isso alimenta o repasse e as evoluções.",
    passos: [
      { texto: "Em **Agendamentos**, ache a sessão do dia." },
      { texto: "No computador, toque no **status** da sessão (por exemplo, **Agendado**) e escolha o novo.", mini: { tipo: "opcoes", itens: ["Finalizado", "Não Compareceu", "Cancelado"], escolhida: "Finalizado" } },
      { texto: "No celular, toque no cartão da sessão, mude o **Status** e toque em **Salvar Alterações**." },
    ],
    dica: "**Finalizado** é quando a sessão aconteceu: o repasse do profissional é lançado sozinho no Financeiro.",
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
  },
  {
    id: "remarcar-uma-sessao",
    titulo: "Remarcar ou desmarcar uma sessão",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Muda o dia ou o horário de uma sessão só, ou apaga essa sessão.",
    passos: [
      { texto: "Em **Agendamentos**, abra a sessão: no computador, pelos **três pontinhos** e **Editar / Detalhes**; no celular, tocando no cartão." },
      { texto: "Para remarcar, mude a **Data**, o **Início** ou o **Fim** e toque em **Salvar Alterações**." },
      { texto: "Para desmarcar, toque em **Excluir**.", mini: { tipo: "botao", texto: "Excluir", variante: "perigo" } },
    ],
    dica: "Se a sessão faz parte de um horário fixo, deixe **Aplicar a toda a série?** desligado para mudar só esta.",
    relacionados: ["mudar-horario-fixo"],
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
  },
  {
    id: "mudar-horario-fixo",
    titulo: "Mudar ou encerrar um horário fixo",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Quando a criança muda de horário de vez, mude todas as sessões seguintes de uma só vez.",
    passos: [
      { texto: "Em **Agendamentos**, abra uma sessão desse horário fixo." },
      { texto: "Mude o dia ou o horário e ligue **Aplicar a toda a série?**.", mini: { tipo: "chave", rotulo: "Aplicar a toda a série?", ligada: true } },
      { texto: "Toque em **Salvar Série Inteira**. Esta sessão e as próximas mudam juntas." },
      { texto: "Para encerrar o horário fixo, com a série ligada, toque em **Excluir Série Futura**." },
    ],
    dica: "Cada sessão mantém o próprio status: as que já foram finalizadas não mudam.",
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
  },
  {
    id: "renovar-pacotes",
    titulo: "Renovar os pacotes que estão acabando",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Quando uma criança chega à última sessão marcada, o sistema avisa para renovar.",
    passos: [
      { texto: "Em **Agendamentos**, toque no botão amarelo **Renovações Pendentes**. Ele só aparece quando há pacote acabando.", mini: { tipo: "botao", texto: "Renovações Pendentes", variante: "amarelo" } },
      { texto: "Em cada criança, escolha a **Frequência** (**Semanal** ou **Quinzenal**) e o número de **Sessões**." },
      { texto: "Toque em **Renovar**. As novas datas são criadas sozinhas." },
    ],
    dica: "A criança não vai continuar? Toque no **X** redondo da linha dela para tirar da lista.",
    tela: { href: "/agendamentos/renovacoes", rotulo: "Ir para Renovações" },
  },
  {
    id: "exportar-relatorio-agenda",
    titulo: "Exportar o relatório da agenda",
    assunto: "agenda",
    papeis: GESTAO,
    resumo: "Gera uma planilha com as sessões de um período, para conferir ou mandar para a contabilidade.",
    passos: [
      { texto: "Em **Agendamentos**, toque em **Exportar Relatório**. No celular, fica nos **três pontinhos**, no alto." },
      { texto: "Escolha o **Profissional** e o **Paciente**, ou deixe todos, e a **Data de Início** e a **Data de Fim**." },
      { texto: "Toque em **Gerar Relatório**. A planilha é baixada no aparelho.", mini: { tipo: "botao", texto: "Gerar Relatório", variante: "principal" } },
    ],
    tela: { href: "/agendamentos", rotulo: "Ir para Agendamentos" },
  },

  // ——— Crianças ———
  {
    id: "ver-ficha-da-crianca",
    titulo: "Ver a ficha de uma criança",
    assunto: "criancas",
    papeis: EQUIPE,
    resumo: "A ficha reúne os dados da criança, os contatos do responsável e o caminho para as evoluções.",
    passos: [
      { texto: "No menu, toque em **Pacientes**." },
      { texto: "Em **Buscar paciente**, escreva o nome da criança ou do responsável.", mini: { tipo: "campo", rotulo: "Buscar paciente", exemplo: "Nome, CPF ou responsável..." } },
      { texto: "Toque nos **três pontinhos** da linha da criança e depois em **Ver Detalhes**." },
    ],
    tela: { href: "/pacientes", rotulo: "Ir para Pacientes" },
  },
  {
    id: "cadastrar-crianca",
    titulo: "Cadastrar uma criança",
    assunto: "criancas",
    papeis: GESTAO,
    resumo: "Toda criança atendida precisa de ficha antes de ser agendada.",
    passos: [
      { texto: "Em **Pacientes**, toque em **Novo Paciente**.", mini: { tipo: "botao", texto: "+ Novo Paciente", variante: "principal" } },
      { texto: "Preencha **Nome Completo**, **Data de Nascimento** e **CPF**. Os campos com * são obrigatórios." },
      { texto: "Em **E-mail para Login (Vínculo)**, escreva o e-mail que a família vai usar para criar a conta no site." },
      { texto: "Preencha o **Contato do Responsável** e o **Endereço** e toque em **Salvar Paciente**." },
    ],
    dica: "O e-mail do vínculo é o que liga a conta da família à criança. A família precisa usar exatamente esse e-mail.",
    tela: { href: "/pacientes/novo", rotulo: "Ir para Novo Paciente" },
  },
  {
    id: "atualizar-ficha",
    titulo: "Atualizar a ficha de uma criança",
    assunto: "criancas",
    papeis: GESTAO,
    resumo: "Telefone novo, convênio novo, endereço novo: tudo se muda pela ficha.",
    passos: [
      { texto: "Em **Pacientes**, ache a criança pela busca." },
      { texto: "Toque nos **três pontinhos** da linha dela e depois em **Editar**." },
      { texto: "Corrija o que mudou e toque em **Salvar Alterações**.", mini: { tipo: "botao", texto: "Salvar Alterações", variante: "principal" } },
    ],
    tela: { href: "/pacientes", rotulo: "Ir para Pacientes" },
  },
  {
    id: "desativar-crianca",
    titulo: "Desativar quem teve alta, sem apagar",
    assunto: "criancas",
    papeis: GESTAO,
    resumo: "A criança sai da lista do dia a dia, mas a história dela fica guardada.",
    passos: [
      { texto: "Em **Pacientes**, ache a criança pela busca." },
      { texto: "Toque nos **três pontinhos** da linha dela e depois em **Desativar**.", mini: { tipo: "botao", texto: "Desativar", variante: "perigo" } },
      { texto: "Confirme. Para trazer de volta, use os mesmos três pontinhos e toque em **Ativar**." },
    ],
    dica: "Para ver quem está desativado, abra **Filtros** e escolha **Inativo** em **Status**.",
    tela: { href: "/pacientes", rotulo: "Ir para Pacientes" },
  },
  {
    id: "exportar-pacientes",
    titulo: "Exportar a lista de pacientes",
    assunto: "criancas",
    papeis: GESTAO,
    resumo: "Gera uma planilha com os pacientes, para abrir no Excel.",
    passos: [
      { texto: "Em **Pacientes**, toque em **Exportar Excel**." },
      { texto: "Em **Filtrar por Status**, escolha quem entra: todos, só os ativos, só os inativos ou só os suspensos." },
      { texto: "Toque em **Baixar Excel**.", mini: { tipo: "botao", texto: "Baixar Excel", variante: "principal" } },
    ],
    tela: { href: "/pacientes", rotulo: "Ir para Pacientes" },
  },

  // ——— Evoluções ———
  {
    id: "escrever-evolucao",
    titulo: "Escrever a evolução de uma sessão",
    assunto: "evolucoes",
    papeis: ["profissional"],
    resumo: "Depois de cada atendimento, você conta o que aconteceu, como fazia no papel. Leva 1 minuto.",
    passos: [
      { texto: "Na tela inicial, toque no aviso amarelo de **evolução para escrever**. Ele aparece quando uma sessão sua termina.", mini: { tipo: "aviso", texto: "1 evolução para escrever, da sessão de hoje", acao: "Escrever" } },
      { texto: "Em **Para escrever**, toque na sessão da criança.", mini: { tipo: "item", titulo: "Lucas Souza", detalhe: "Hoje, 09:00 · Fonoaudiologia" } },
      { texto: "Escreva no campo **O que aconteceu na sessão**: o que foi trabalhado, como a criança respondeu e o que orientar à família.", mini: { tipo: "campo", rotulo: "O que aconteceu na sessão", exemplo: "Conte como foi a sessão…" } },
      { texto: "Toque em **Salvar evolução**. Pronto: a sessão sai da lista.", mini: { tipo: "botao", texto: "Salvar evolução", variante: "principal" } },
    ],
    dica: "A criança faltou? Em vez de escrever, toque em **A sessão não aconteceu**.",
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
    relacionados: ["sessao-nao-aconteceu", "corrigir-evolucao"],
  },
  {
    id: "sessao-nao-aconteceu",
    titulo: "Avisar que a sessão não aconteceu",
    assunto: "evolucoes",
    papeis: ["profissional"],
    resumo: "Se a criança faltou ou a sessão foi cancelada, avise em vez de escrever. A sessão sai das pendentes.",
    passos: [
      { texto: "Em **Evoluções**, toque na sessão em **Para escrever**." },
      { texto: "Toque em **A sessão não aconteceu** e confirme.", mini: { tipo: "botao", texto: "A sessão não aconteceu", variante: "contorno" } },
    ],
    dica: "Se a recepção marcou presença nessa sessão, ela aparece para a coordenação conferir.",
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
  },
  {
    id: "corrigir-evolucao",
    titulo: "Corrigir ou apagar uma evolução",
    assunto: "evolucoes",
    papeis: ["profissional"],
    resumo: "Errou ou esqueceu algo? Você pode corrigir as suas evoluções a qualquer momento.",
    passos: [
      { texto: "Em **Evoluções**, ache a evolução em **Escritas nos últimos 14 dias** e toque nela." },
      { texto: "Toque em **Corrigir**, mude o texto e toque em **Salvar correção**.", mini: { tipo: "botao", texto: "Salvar correção", variante: "principal" } },
      { texto: "Para apagar, toque em **Apagar evolução** e confirme. Se você tinha marcado que não aconteceu, o botão é **Desfazer**." },
    ],
    dica: "Evoluções mais antigas ficam na história da criança, na parte de baixo da tela de **Evoluções**.",
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
  },
  {
    id: "abrir-prontuario",
    titulo: "Abrir o prontuário de uma criança",
    assunto: "evolucoes",
    papeis: ["admin", "coordenador", "profissional"],
    resumo: "O prontuário reúne, por terapia, o que é preciso lembrar, as anotações da equipe e a história das evoluções.",
    passos: [
      { texto: "No menu, toque em **Prontuários**.", mini: { tipo: "opcoes", itens: ["Pacientes", "Prontuários", "Evoluções"], escolhida: "Prontuários" } },
      { texto: "Ache a criança na lista ou em **Buscar criança** e toque no nome dela. O terapeuta vê só as crianças que atende.", mini: { tipo: "campo", rotulo: "Buscar criança", exemplo: "Buscar criança" } },
      { texto: "Escolha a terapia nas abas do alto. Em **Anotações** fica o que a equipe anotou; em **Evoluções**, a história das sessões.", mini: { tipo: "opcoes", itens: ["Anotações", "Evoluções"], escolhida: "Anotações" } },
    ],
    dica: "Também dá pela ficha da criança (Pacientes → Ver Detalhes → **Abrir prontuário**) e pela janela da evolução.",
    tela: { href: "/prontuario", rotulo: "Ir para Prontuários" },
    relacionados: ["escrever-anotacao"],
  },
  {
    id: "escrever-anotacao",
    titulo: "Escrever no prontuário",
    assunto: "evolucoes",
    papeis: ["profissional"],
    resumo: "Anote o que vale para toda a terapia da criança: objetivos, o que funciona, o que evitar, combinados com a família.",
    passos: [
      { texto: "Abra o prontuário da criança e fique na aba da sua terapia, a marcada **sua**." },
      { texto: "Toque em **Nova anotação** e escreva em **O que você quer anotar?**.", mini: { tipo: "campo", rotulo: "O que você quer anotar?", exemplo: "Começar pelo jogo de encaixe…" } },
      { texto: "Se é algo para lembrar sempre, ligue **Fixar em “Para lembrar”**. Toque em **Salvar anotação**.", mini: { tipo: "chave", rotulo: "Fixar em “Para lembrar”", ligada: true } },
    ],
    dica: "O que está em **Para lembrar** também aparece em cima, na hora de escrever a evolução. Errou? Toque em **Corrigir**: anotações não são apagadas, porque fazem parte do prontuário.",
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
  },
  {
    id: "acompanhar-evolucoes",
    titulo: "Acompanhar quem está em dia",
    assunto: "evolucoes",
    papeis: ["admin", "coordenador"],
    resumo: "Veja quais sessões já têm evolução, quais estão pendentes e quem está em dia.",
    passos: [
      { texto: "No menu, toque em **Evoluções**. Escolha o período no alto: **Hoje**, **Ontem**, **7 dias**, **14 dias** ou **Escolher datas**.", mini: { tipo: "opcoes", itens: ["Hoje", "Ontem", "7 dias", "14 dias"], escolhida: "7 dias" } },
      { texto: "Os números coloridos mostram as **Escritas**, as **Pendentes**, as que **não batem com a recepção** e as que **não aconteceram**. Toque num número para ver só aquelas sessões." },
      { texto: "Cada terapeuta mostra se está **Em dia** ou quantas faltam, com quem tem pendência primeiro. Toque no terapeuta para ver só as sessões dele. No celular, a página já abre por esses cartões.", mini: { tipo: "item", titulo: "Lia", detalhe: "Terapia Ocupacional · 9 em dia", selo: "17 pendentes" } },
    ],
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
    relacionados: ["ler-evolucoes", "conferir-incompativeis"],
  },
  {
    id: "ler-evolucoes",
    titulo: "Ler as evoluções da equipe",
    assunto: "evolucoes",
    papeis: ["admin", "coordenador"],
    resumo: "Leia o que cada terapeuta escreveu, uma evolução atrás da outra, sem sair da tela.",
    passos: [
      { texto: "Em **Evoluções**, use **Buscar criança** ou os filtros de **Terapeuta**, **Terapia** e **Situação** para achar o que procura. No celular, toque antes num terapeuta ou num número.", mini: { tipo: "campo", rotulo: "Buscar criança", exemplo: "Buscar criança" } },
      { texto: "Toque numa sessão da lista. A evolução aparece ao lado, com a anterior da mesma terapia embaixo. No celular, ela abre por cima da lista." },
      { texto: "Toque em **Próxima** para ler a seguinte da lista, ou em **Anterior** para voltar.", mini: { tipo: "botao", texto: "Próxima ›", variante: "principal" } },
      { texto: "A lista mostra 20 sessões por vez. Para ver as outras, toque em **Mostrar mais**, no fim dela." },
    ],
    dica: "Para ver tudo o que uma criança já teve, desde o começo, toque em **Abrir prontuário** na evolução, ou use **Prontuários**, no menu.",
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
  },
  {
    id: "conferir-incompativeis",
    titulo: "Conferir as evoluções que não batem com a recepção",
    assunto: "evolucoes",
    papeis: ["admin", "coordenador"],
    resumo: "Quando o terapeuta escreve sobre uma sessão que a recepção marcou como falta, por exemplo, ela aparece para conferir.",
    passos: [
      { texto: "Em **Evoluções**, toque no número **Não bate com a recepção**. A lista mostra só essas sessões.", mini: { tipo: "botao", texto: "1 Não bate com a recepção", variante: "contorno" } },
      { texto: "Toque na sessão: o aviso diz o que não bateu. Confira com a recepção e com o terapeuta o que aconteceu de verdade." },
      { texto: "Se a recepção marcou errado, corrija o status na **Agenda**. Se a evolução está errada, o terapeuta corrige ou apaga." },
    ],
    tela: { href: "/evolucoes", rotulo: "Ir para Evoluções" },
  },

  // ——— Equipe, terapias e salas ———
  {
    id: "cadastrar-profissional",
    titulo: "Cadastrar um profissional",
    assunto: "equipe",
    papeis: GESTAO,
    resumo: "Cada terapeuta precisa de cadastro para aparecer na agenda.",
    passos: [
      { texto: "No menu, toque em **Profissionais** e depois em **Novo Profissional**." },
      { texto: "Preencha **Nome Completo**, **Especialidade**, **Email**, **CPF** e **Celular**." },
      { texto: "Em **Dias e Horários de Atendimento**, marque os dias e o horário em que a pessoa atende." },
      { texto: "Toque em **Salvar Profissional**.", mini: { tipo: "botao", texto: "Salvar Profissional", variante: "principal" } },
    ],
    tela: { href: "/profissionais", rotulo: "Ir para Profissionais" },
    relacionados: ["configurar-repasse"],
  },
  {
    id: "configurar-repasse",
    titulo: "Configurar o repasse do profissional",
    assunto: "equipe",
    papeis: ["admin", "coordenador"],
    resumo: "Com o repasse configurado, cada sessão finalizada lança sozinha o valor a pagar ao profissional.",
    passos: [
      { texto: "Em **Profissionais**, toque nos **três pontinhos** do profissional e depois em **Editar**." },
      { texto: "Em **Tipo de Pagamento**, escolha **Repasse** (porcentagem), **Fixo** ou **Ambos**." },
      { texto: "Preencha o **Repasse Padrão (%)**." },
      { texto: "Se alguma terapia paga diferente, em **Regras Especiais de Repasse** escolha a especialidade, o percentual e toque em **Adicionar Regra**." },
      { texto: "Toque em **Salvar Alterações**." },
    ],
    tela: { href: "/profissionais", rotulo: "Ir para Profissionais" },
  },
  {
    id: "cadastrar-terapia",
    titulo: "Cadastrar uma terapia e o valor dela",
    assunto: "equipe",
    papeis: ["admin"],
    resumo: "As terapias (especialidades) e os valores aparecem na hora de agendar.",
    passos: [
      { texto: "No menu, toque em **Especialidades** e depois em **Nova Especialidade**." },
      { texto: "Preencha o **Nome da Especialidade** e o **Valor da Consulta (R$)**.", mini: { tipo: "campo", rotulo: "Nome da Especialidade *", exemplo: "Fonoaudiologia" } },
      { texto: "Toque em **Salvar**." },
    ],
    tela: { href: "/especialidades", rotulo: "Ir para Especialidades" },
  },
  {
    id: "ver-ocupacao-das-salas",
    titulo: "Ver quais salas estão livres",
    assunto: "equipe",
    papeis: GESTAO,
    resumo: "Mostra cada sala, se está ocupada agora e a agenda dela no dia.",
    passos: [
      { texto: "No menu, toque em **Mapeamento de Salas**." },
      { texto: "Cada sala mostra se está **Ocupada** ou **Livre** agora e os horários da **Agenda do Dia**. Toque na sala para ver mais.", mini: { tipo: "item", titulo: "Sala 101", detalhe: "Sala Azul · Agenda do Dia: 07:20, 08:10", selo: "Livre" } },
      { texto: "Para ver outro dia, mude a **Data de Visualização**." },
    ],
    tela: { href: "/mapeamento-salas", rotulo: "Ir para Mapeamento de Salas" },
  },
  {
    id: "cadastrar-sala",
    titulo: "Cadastrar ou mudar uma sala",
    assunto: "equipe",
    papeis: GESTAO,
    resumo: "As salas cadastradas aparecem para escolher na hora de agendar.",
    passos: [
      { texto: "Em **Mapeamento de Salas**, toque em **Gerir Salas** para criar uma sala nova." },
      { texto: "Preencha **Nome da Sala**, **Número**, **Andar** e **Tipo de Sala** e toque em **Salvar**." },
      { texto: "Para mudar uma sala que já existe, toque no cartão dela e depois em **Editar Sala**." },
    ],
    dica: "Sala parada para conserto? Mude o **Status** dela para **Em Manutenção**.",
    tela: { href: "/mapeamento-salas", rotulo: "Ir para Mapeamento de Salas" },
  },

  // ——— Financeiro ———
  {
    id: "lancar-movimentacao",
    titulo: "Lançar uma entrada ou uma saída",
    assunto: "financeiro",
    papeis: ["admin"],
    resumo: "Registra um recebimento (receita) ou um pagamento (despesa) da clínica.",
    passos: [
      { texto: "No menu, toque em **Financeiro** e depois em **Nova Movimentação**.", mini: { tipo: "botao", texto: "+ Nova Movimentação", variante: "principal" } },
      { texto: "Em **Tipo**, escolha **Receita** (entrou dinheiro) ou **Despesa** (saiu dinheiro)." },
      { texto: "Preencha **Descrição**, **Valor**, **Data de Movimento**, **Plano de Contas** e **Centro de Custo**." },
      { texto: "Em **Status**, escolha **Pago** se já aconteceu ou **Pendente** se ainda vai acontecer, e toque em **Salvar Movimentação**." },
    ],
    tela: { href: "/financeiro", rotulo: "Ir para o Financeiro" },
  },
  {
    id: "baixa-no-repasse",
    titulo: "Dar baixa num repasse pago",
    assunto: "financeiro",
    papeis: ["admin"],
    resumo: "Os repasses são lançados sozinhos quando a sessão é finalizada. Depois de pagar o profissional, dê baixa.",
    passos: [
      { texto: "Em **Financeiro**, abra a aba **Despesas** e depois **Apenas Repasses**.", mini: { tipo: "opcoes", itens: ["Despesas Gerais", "Apenas Repasses"], escolhida: "Apenas Repasses" } },
      { texto: "Ache o repasse e toque nos **três pontinhos** da linha dele." },
      { texto: "Toque em **Marcar como Pago**." },
    ],
    tela: { href: "/financeiro", rotulo: "Ir para o Financeiro" },
  },
  {
    id: "fluxo-de-caixa",
    titulo: "Ver o fluxo de caixa",
    assunto: "financeiro",
    papeis: ["admin"],
    resumo: "Mostra o que entrou e o que saiu no período, para fechar o mês.",
    passos: [
      { texto: "Em **Financeiro**, abra a aba **Relatórios**." },
      { texto: "Toque em **Fluxo de Caixa**. Na mesma aba ficam as **Contas a Pagar**, as **Contas a Receber** e outros relatórios." },
    ],
    tela: { href: "/financeiro", rotulo: "Ir para o Financeiro" },
  },

  // ——— Comercial ———
  {
    id: "cadastrar-interessado",
    titulo: "Cadastrar uma família interessada",
    assunto: "comercial",
    papeis: ["admin", "coordenador"],
    resumo: "Quem procura a clínica entra no funil, para ninguém ficar sem resposta.",
    passos: [
      { texto: "No menu, toque em **Comercial** e depois em **Novo Paciente**." },
      { texto: "Preencha o **Nome do Paciente** e o **Contato (Telefone)**." },
      { texto: "Escolha o **Tipo de Fluxo** e, se veio de uma parceria ou evento, o **Evento de Origem**. Toque em **Salvar**." },
    ],
    tela: { href: "/comercial", rotulo: "Ir para o Comercial" },
    relacionados: ["mover-no-funil"],
  },
  {
    id: "mover-no-funil",
    titulo: "Passar o interessado para a próxima etapa",
    assunto: "comercial",
    papeis: ["admin", "coordenador"],
    resumo: "Cada coluna do funil é um setor. O cartão anda conforme o atendimento avança.",
    passos: [
      { texto: "Em **Comercial**, ache o cartão da família. A busca fica no alto." },
      { texto: "Marque as tarefas já feitas, na lista dentro do cartão." },
      { texto: "Em **Mover...**, escolha a próxima etapa.", mini: { tipo: "campo", rotulo: "Etapa", exemplo: "Mover..." } },
    ],
    tela: { href: "/comercial", rotulo: "Ir para o Comercial" },
  },

  // ——— Avisos e mensagens ———
  {
    id: "ler-avisos",
    titulo: "Ler os avisos da clínica",
    assunto: "avisos",
    papeis: ["profissional", "familiar"],
    resumo: "Recados da clínica para você. Os importantes pedem que você confirme que leu.",
    passos: [
      { texto: "Toque no **sino**, no alto da tela, ou em **Avisos**, no menu." },
      { texto: "Os importantes ficam em cima, em **Precisa da sua atenção**." },
      { texto: "Depois de ler um aviso importante, toque em **Estou ciente**.", mini: { tipo: "botao", texto: "Estou ciente", variante: "principal" } },
    ],
    tela: { href: "/comunicacao", rotulo: "Ir para Avisos" },
  },
  {
    id: "enviar-aviso",
    titulo: "Enviar um aviso",
    assunto: "avisos",
    papeis: GESTAO,
    resumo: "Manda um recado para a equipe, só para os terapeutas, para a coordenação ou para todas as famílias.",
    passos: [
      { texto: "No menu, toque em **Avisos** e depois em **Novo aviso**." },
      { texto: "Em **Para quem**, escolha quem recebe.", mini: { tipo: "opcoes", itens: ["Equipe toda", "Terapeutas", "Coordenação", "Famílias"], escolhida: "Equipe toda" } },
      { texto: "Escreva o **Título** e a **Mensagem**." },
      { texto: "Se todos precisam confirmar que leram, ligue **Importante**. Toque no botão **Enviar**, que mostra quantas pessoas vão receber.", mini: { tipo: "chave", rotulo: "Importante", ligada: true } },
    ],
    tela: { href: "/comunicacao", rotulo: "Ir para Avisos" },
    relacionados: ["quem-leu"],
  },
  {
    id: "quem-leu",
    titulo: "Ver quem já leu um aviso",
    assunto: "avisos",
    papeis: GESTAO,
    resumo: "Cada aviso mostra quantas pessoas já leram e quem ainda não leu.",
    passos: [
      { texto: "Em **Avisos**, a coluna **Leitura** mostra quantos já leram cada aviso." },
      { texto: "Toque no aviso para ver os nomes em **Já leram** e **Ainda não leram**." },
    ],
    tela: { href: "/comunicacao", rotulo: "Ir para Avisos" },
  },
  {
    id: "conversar-mensagens",
    titulo: "Conversar pelo Mensagens",
    assunto: "avisos",
    papeis: TODOS,
    resumo: "Cada criança tem uma conversa com a família e a equipe que cuida dela.",
    passos: [
      { texto: "No menu, toque em **Mensagens**. As conversas com mensagem nova têm um número ao lado." },
      { texto: "Toque na conversa da criança. Para achar mais rápido, use **Buscar pelo nome da criança**.", mini: { tipo: "campo", rotulo: "Buscar", exemplo: "Buscar pelo nome da criança" } },
      { texto: "Escreva em **Escreva uma mensagem** e toque no **aviãozinho** para enviar." },
    ],
    tela: { href: "/mensagens", rotulo: "Ir para Mensagens" },
  },
  {
    id: "criar-grupo",
    titulo: "Criar a conversa de uma criança",
    assunto: "avisos",
    papeis: ["admin", "coordenador"],
    resumo: "Junta a família e a equipe da criança numa conversa só.",
    passos: [
      { texto: "Em **Mensagens**, toque em **Novo grupo**." },
      { texto: "Escolha a criança. O sistema já sugere a família e os terapeutas dela." },
      { texto: "Confira as pessoas e toque em **Criar grupo**.", mini: { tipo: "botao", texto: "Criar grupo (4 pessoas)", variante: "principal" } },
    ],
    tela: { href: "/mensagens", rotulo: "Ir para Mensagens" },
  },

  // ——— Acessos ———
  {
    id: "aprovar-acesso",
    titulo: "Aprovar quem pediu acesso",
    assunto: "acessos",
    papeis: ["admin"],
    resumo: "Quem cria conta no site só entra depois da sua aprovação.",
    passos: [
      { texto: "No menu, toque em **Aprovação de Acesso**. A tela inicial também avisa quando há pedidos." },
      { texto: "Confira o nome, o e-mail e o perfil de cada pedido." },
      { texto: "Toque em **Aprovar** ou em **Rejeitar**.", mini: { tipo: "botao", texto: "Aprovar", variante: "principal" } },
    ],
    dica: "Família só deve ser aprovada se o e-mail for o mesmo da ficha da criança.",
    tela: { href: "/admin/usuarios", rotulo: "Ir para Aprovação de Acesso" },
  },
  {
    id: "senha-provisoria",
    titulo: "Dar uma senha provisória para quem esqueceu a senha",
    assunto: "acessos",
    papeis: ["admin"],
    resumo: "Para quando o e-mail de recuperação não chega: você define uma senha, passa para a pessoa e ela cria a dela ao entrar.",
    passos: [
      { texto: "Em **Gerenciar Usuários**, ache a pessoa e toque na **chave**, ao lado da lixeira.", mini: { tipo: "botao", texto: "Chave: Senha provisória", variante: "contorno" } },
      { texto: "O sistema já sugere uma senha fácil de ditar. Se quiser outra, toque em **Gerar outra**. Depois, toque em **Definir senha**." },
      { texto: "Toque em **Copiar** e mande a senha para a pessoa, por WhatsApp por exemplo.", mini: { tipo: "campo", rotulo: "Senha definida", exemplo: "libelle-482193" } },
      { texto: "Quando a pessoa entrar com essa senha, o sistema pede para ela criar uma senha nova antes de qualquer outra tela." },
    ],
    dica: "A senha não fica guardada no sistema: copie na hora. Se perder, é só definir outra.",
    tela: { href: "/admin/gerenciar-usuarios", rotulo: "Ir para Gerenciar Usuários" },
  },
  {
    id: "mudar-papel",
    titulo: "Mudar o perfil de alguém",
    assunto: "acessos",
    papeis: ["admin"],
    resumo: "O perfil decide o que a pessoa vê: Familiar, Profissional, Funcionário, Coordenador ou Admin.",
    passos: [
      { texto: "No menu, toque em **Gerenciar Usuários**." },
      { texto: "Ache a pessoa na lista. As abas do alto separam por perfil." },
      { texto: "Na coluna **Ação**, abra a caixinha ao lado da lixeira e escolha o novo perfil. A mudança vale na hora.", mini: { tipo: "opcoes", itens: ["Profissional", "Funcionário", "Coordenador"], escolhida: "Coordenador" } },
      { texto: "Ao escolher **Profissional**, o sistema liga a conta ao cadastro da pessoa em **Profissionais** (pelo CPF ou pelo e-mail). É assim que aparecem as sessões dela e dá para escrever as evoluções." },
    ],
    dica: "Se aparecer \"Sem cadastro em Profissionais\", crie o cadastro em Novo Profissional com o mesmo CPF ou e-mail e abra Gerenciar Usuários de novo: a ligação é feita sozinha.",
    tela: { href: "/admin/gerenciar-usuarios", rotulo: "Ir para Gerenciar Usuários" },
  },
  {
    id: "tirar-acesso",
    titulo: "Tirar o acesso de quem saiu",
    assunto: "acessos",
    papeis: ["admin"],
    resumo: "A pessoa deixa de entrar no sistema. Os registros que ela fez continuam guardados.",
    passos: [
      { texto: "Em **Gerenciar Usuários**, ache a pessoa." },
      { texto: "Toque na **lixeira** da linha dela." },
      { texto: "Confira o nome e toque em **Sim, excluir acesso**.", mini: { tipo: "botao", texto: "Sim, excluir acesso", variante: "perigo" } },
    ],
    dica: "Não dá para desfazer: se a pessoa voltar, ela precisa criar a conta de novo.",
    tela: { href: "/admin/gerenciar-usuarios", rotulo: "Ir para Gerenciar Usuários" },
  },

  // ——— Regras do sistema ———
  {
    id: "regra-sessao-para-escrever",
    titulo: "Por que uma sessão aparece (ou não) para escrever a evolução",
    assunto: "regras",
    papeis: ["admin", "coordenador", "profissional"],
    resumo: "A sessão só aparece em Para escrever quando todas estas condições valem ao mesmo tempo.",
    passos: [
      { texto: "A sessão está na **agenda**, no nome do terapeuta. Se está no nome de outra pessoa, a recepção corrige na agenda." },
      { texto: "O **horário de fim** marcado na agenda já passou. Terminou mais cedo? A sessão aparece quando der o horário de fim." },
      { texto: "A recepção **não marcou falta nem cancelamento**. Nesses casos, a sessão não pede evolução." },
      { texto: "A sessão é de **06/10/2026** em diante (quando as evoluções começaram no sistema) e dos **últimos 14 dias**." },
    ],
    dica: "Com o site aberto desde cedo, uma mudança da recepção só aparece depois de **recarregar a página**. No celular, puxe a tela para baixo.",
    relacionados: ["regra-pendente-atrasada"],
  },
  {
    id: "regra-pendente-atrasada",
    titulo: "Quando a evolução fica pendente e quando fica atrasada",
    assunto: "regras",
    papeis: ["admin", "coordenador", "profissional"],
    resumo: "A cobrança segue o relógio da agenda, sem esperar a recepção marcar presença.",
    passos: [
      { texto: "A sessão vira **pendente** assim que acaba o horário dela na agenda." },
      { texto: "A partir do dia seguinte, ela aparece como **atrasada**, em vermelho, com há quantos dias." },
      { texto: "Ela sai da lista quando o terapeuta escreve a evolução, quando avisa que **a sessão não aconteceu** ou quando a recepção marca falta ou cancelamento." },
      { texto: "A lista olha os **últimos 14 dias**: escreva antes disso, porque sessões mais antigas saem da lista." },
    ],
  },
  {
    id: "regra-nao-bate",
    titulo: "O que é “Não bate com a recepção”",
    assunto: "regras",
    papeis: ["admin", "coordenador", "profissional"],
    resumo: "É quando o que o terapeuta registrou não combina com o que a recepção marcou na agenda.",
    passos: [
      { texto: "O terapeuta **escreveu a evolução**, mas a recepção marcou **falta** ou **cancelamento**." },
      { texto: "Ou o terapeuta avisou que **a sessão não aconteceu**, mas a recepção marcou **Finalizado**." },
      { texto: "Ninguém é bloqueado: a evolução ganha o aviso e a coordenação confere. Quem errou corrige: a recepção na agenda ou o terapeuta na evolução." },
    ],
  },
  {
    id: "regra-quem-ve",
    titulo: "Quem vê as evoluções e o prontuário",
    assunto: "regras",
    papeis: ["admin", "coordenador", "funcionario", "profissional"],
    resumo: "Evoluções e prontuário são dados de saúde: cada pessoa vê só o que precisa.",
    passos: [
      { texto: "Leem o **admin**, a **coordenação** e os **terapeutas que atendem a criança**." },
      { texto: "A **recepção** e a **família** não veem evoluções nem prontuário." },
      { texto: "Cada terapeuta escreve só a evolução das **sessões dele** e só anota no prontuário da **terapia dele**." },
      { texto: "Anotações do prontuário **não são apagadas**: quem escreveu pode corrigir, e ela fica marcada como editada. A evolução só pode ser corrigida ou apagada por quem escreveu." },
    ],
  },
  {
    id: "regra-status-da-sessao",
    titulo: "O que cada status da sessão faz",
    assunto: "regras",
    papeis: ["admin", "coordenador", "funcionario"],
    resumo: "O status que a recepção marca na agenda mexe no Financeiro e nas evoluções.",
    passos: [
      { texto: "**Finalizado**: a sessão aconteceu. O repasse do profissional é lançado sozinho no Financeiro.", mini: { tipo: "opcoes", itens: ["Finalizado", "Não Compareceu", "Cancelado"], escolhida: "Finalizado" } },
      { texto: "**Não Compareceu** (falta) e **Cancelado**: a sessão não pede evolução." },
      { texto: "**Agendado**: ainda não foi marcada. Mesmo assim, a evolução já é pedida ao terapeuta quando acaba o horário." },
      { texto: "Mudar um **horário fixo** com **Aplicar a toda a série?** muda as próximas sessões, e cada uma mantém o próprio status." },
    ],
    relacionados: ["presenca-falta", "mudar-horario-fixo"],
  },
  {
    id: "regra-acesso",
    titulo: "Como funciona o acesso ao sistema",
    assunto: "regras",
    papeis: ["admin"],
    resumo: "Quem entra, quando entra e o que acontece quando o acesso sai.",
    passos: [
      { texto: "Toda conta nova começa **pendente** e só entra depois que o admin **aprova**." },
      { texto: "A família vê só as crianças cujo **E-mail para Login (Vínculo)**, na ficha, é o mesmo e-mail da conta dela." },
      { texto: "O **perfil** decide o que cada pessoa vê no menu: Familiar, Profissional, Funcionário (recepção), Coordenador ou Admin." },
      { texto: "O terapeuta só vê as sessões dele quando a conta está ligada ao cadastro em **Profissionais**. A aprovação e a troca para Profissional fazem essa ligação sozinhas, pelo CPF ou pelo e-mail." },
      { texto: "Quem tem o **acesso tirado** não entra mais no sistema. O que a pessoa registrou continua guardado." },
    ],
    relacionados: ["aprovar-acesso", "mudar-papel", "senha-provisoria"],
  },
  {
    id: "regra-senha-provisoria",
    titulo: "Recebi uma senha provisória: o que fazer",
    assunto: "regras",
    papeis: TODOS,
    resumo: "Quando a clínica redefine a sua senha, você entra com a senha que recebeu e cria uma só sua.",
    passos: [
      { texto: "Entre com o seu e-mail e a **senha provisória** que a clínica mandou." },
      { texto: "O sistema abre **Crie uma senha nova**. Nenhuma outra tela abre antes de trocar." },
      { texto: "A senha nova precisa ter **pelo menos 6 caracteres** e ser **diferente da provisória**. Escreva duas vezes, igual, e toque em **Salvar e entrar**." },
    ],
    dica: "Esqueceu a senha e o e-mail de recuperação não chega? Peça à administração uma senha provisória.",
  },
];
